### ISSUE TITLE
CSS Modules内でのプライベートクラスっぽいやつの扱いを考える

### ISSUE THREAD

**Issue by yasaichi** [yasaichi/minesweeper-reactjs#18]
タイトル通り。例えば

``` css
/* 基底クラス的なの */
.base {
  float: left;
  display: inline-block;
  width: var(--side-length);
  height: var(--side-length);
  box-sizing: border-box;
  text-align: center;
}

.revealed {
  composes: base;
  border: 2px solid #6d6d6d;
  font-weight: bold;
  line-height: calc(var(--side-length) - 2px * 2);
}

.unrevealed {
  composes: bump from '../shared/styles/box.css';
  composes: base;
  line-height: calc(var(--side-length) - 4px * 2);
}

/* ここから先が実際に使うの */
.marked {
  composes: fontAwesome from '../shared/styles/typography.css';
  composes: unrevealed;
  color: #fb0000;
}

.mined {
  composes: fontAwesome from '../shared/styles/typography.css';
  composes: revealed;
  background-color: #fb0000;
}

.number1 {
  composes: revealed;
  color: var(--number-color-1);
}
```

みたいなCSSがあったときに、基底クラスは公開しないつもりで書いているのでこれを明示orプログラム的に`import`できないようにする仕組みを考える。
